export const SET_HOMEDATE_SUCCESS = "SET_HOMEDATE_SUCCESS";
export const ERROR_HOMEDATA = "ERROR_HOMEDATA";
export const RESET_HOME = "RESET_HOME";
export const SET_DETAIL_DATA = "SET_DETAIL_DATA";
export const ERROR_DETAIL_DATA = "ERROR_DETAIL_DATA";
export const RESET_DETAIL = "RESET_DETAIL";